package com.github.jamsa.rap.model;

import com.github.jamsa.rap.core.model.BaseEntity;
import java.util.Date;

public class DictValue extends BaseEntity<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.DICT_VALUE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer dictValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.DICT_TYPE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer dictTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.CODE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer lastUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_DICT_VALUE.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.DICT_VALUE_ID
     *
     * @return the value of RAP_DICT_VALUE.DICT_VALUE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getDictValueId() {
        return dictValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.DICT_VALUE_ID
     *
     * @param dictValueId the value for RAP_DICT_VALUE.DICT_VALUE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setDictValueId(Integer dictValueId) {
        this.firePropertyChange("dictValueId",dictValueId);
        this.dictValueId = dictValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.DICT_TYPE_ID
     *
     * @return the value of RAP_DICT_VALUE.DICT_TYPE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getDictTypeId() {
        return dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.DICT_TYPE_ID
     *
     * @param dictTypeId the value for RAP_DICT_VALUE.DICT_TYPE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setDictTypeId(Integer dictTypeId) {
        this.firePropertyChange("dictTypeId",dictTypeId);
        this.dictTypeId = dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.CODE
     *
     * @return the value of RAP_DICT_VALUE.CODE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.CODE
     *
     * @param code the value for RAP_DICT_VALUE.CODE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCode(String code) {
        this.firePropertyChange("code",code);
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.VALUE
     *
     * @return the value of RAP_DICT_VALUE.VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.VALUE
     *
     * @param value the value for RAP_DICT_VALUE.VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setValue(String value) {
        this.firePropertyChange("value",value);
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.CREATED_BY
     *
     * @return the value of RAP_DICT_VALUE.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.CREATED_BY
     *
     * @param createdBy the value for RAP_DICT_VALUE.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCreatedBy(Integer createdBy) {
        this.firePropertyChange("createdBy",createdBy);
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.CREATION_DATE
     *
     * @return the value of RAP_DICT_VALUE.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.CREATION_DATE
     *
     * @param creationDate the value for RAP_DICT_VALUE.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.firePropertyChange("creationDate",creationDate);
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.LAST_UPDATE_DATE
     *
     * @return the value of RAP_DICT_VALUE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for RAP_DICT_VALUE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.firePropertyChange("lastUpdateDate",lastUpdateDate);
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.LAST_UPDATED_BY
     *
     * @return the value of RAP_DICT_VALUE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for RAP_DICT_VALUE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setLastUpdatedBy(Integer lastUpdatedBy) {
        this.firePropertyChange("lastUpdatedBy",lastUpdatedBy);
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_DICT_VALUE.MEMO
     *
     * @return the value of RAP_DICT_VALUE.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_DICT_VALUE.MEMO
     *
     * @param memo the value for RAP_DICT_VALUE.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setMemo(String memo) {
        this.firePropertyChange("memo",memo);
        this.memo = memo;
    }

    public Integer getPrimaryKey() {
        return this.dictValueId;
    }

    public void setPrimaryKey(Integer pkValue) {
        this.setDictValueId(pkValue);
    }
}