package com.github.jamsa.rap.model;

import com.github.jamsa.rap.core.model.BaseEntity;
import java.util.Date;

public class Resource extends BaseEntity<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.NAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.CODE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.TYPE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.URL
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_RESOURCE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer lastUpdatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.RESOURCE_ID
     *
     * @return the value of RAP_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.RESOURCE_ID
     *
     * @param resourceId the value for RAP_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setResourceId(Integer resourceId) {
        this.firePropertyChange("resourceId",resourceId);
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.NAME
     *
     * @return the value of RAP_RESOURCE.NAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.NAME
     *
     * @param name the value for RAP_RESOURCE.NAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setName(String name) {
        this.firePropertyChange("name",name);
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.CODE
     *
     * @return the value of RAP_RESOURCE.CODE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.CODE
     *
     * @param code the value for RAP_RESOURCE.CODE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCode(String code) {
        this.firePropertyChange("code",code);
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.TYPE
     *
     * @return the value of RAP_RESOURCE.TYPE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.TYPE
     *
     * @param type the value for RAP_RESOURCE.TYPE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setType(String type) {
        this.firePropertyChange("type",type);
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.URL
     *
     * @return the value of RAP_RESOURCE.URL
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.URL
     *
     * @param url the value for RAP_RESOURCE.URL
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setUrl(String url) {
        this.firePropertyChange("url",url);
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.MEMO
     *
     * @return the value of RAP_RESOURCE.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.MEMO
     *
     * @param memo the value for RAP_RESOURCE.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setMemo(String memo) {
        this.firePropertyChange("memo",memo);
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.CREATED_BY
     *
     * @return the value of RAP_RESOURCE.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.CREATED_BY
     *
     * @param createdBy the value for RAP_RESOURCE.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCreatedBy(Integer createdBy) {
        this.firePropertyChange("createdBy",createdBy);
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.CREATION_DATE
     *
     * @return the value of RAP_RESOURCE.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.CREATION_DATE
     *
     * @param creationDate the value for RAP_RESOURCE.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.firePropertyChange("creationDate",creationDate);
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.LAST_UPDATE_DATE
     *
     * @return the value of RAP_RESOURCE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for RAP_RESOURCE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.firePropertyChange("lastUpdateDate",lastUpdateDate);
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_RESOURCE.LAST_UPDATED_BY
     *
     * @return the value of RAP_RESOURCE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_RESOURCE.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for RAP_RESOURCE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setLastUpdatedBy(Integer lastUpdatedBy) {
        this.firePropertyChange("lastUpdatedBy",lastUpdatedBy);
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public Integer getPrimaryKey() {
        return this.resourceId;
    }

    public void setPrimaryKey(Integer pkValue) {
        this.setResourceId(pkValue);
    }
}