package com.github.jamsa.rap.model;

import com.github.jamsa.rap.core.model.BaseEntity;
import java.util.Date;

public class User extends BaseEntity<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.USER_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.USERNAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.FULLNAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.TEL
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.BIRTHDAY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private Integer lastUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.USER_ID
     *
     * @return the value of RAP_USER.USER_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.USER_ID
     *
     * @param userId the value for RAP_USER.USER_ID
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setUserId(Integer userId) {
        this.firePropertyChange("userId",userId);
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.USERNAME
     *
     * @return the value of RAP_USER.USERNAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.USERNAME
     *
     * @param username the value for RAP_USER.USERNAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setUsername(String username) {
        this.firePropertyChange("username",username);
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.PASSWORD
     *
     * @return the value of RAP_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.PASSWORD
     *
     * @param password the value for RAP_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setPassword(String password) {
        this.firePropertyChange("password",password);
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.FULLNAME
     *
     * @return the value of RAP_USER.FULLNAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.FULLNAME
     *
     * @param fullname the value for RAP_USER.FULLNAME
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setFullname(String fullname) {
        this.firePropertyChange("fullname",fullname);
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.TEL
     *
     * @return the value of RAP_USER.TEL
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.TEL
     *
     * @param tel the value for RAP_USER.TEL
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setTel(String tel) {
        this.firePropertyChange("tel",tel);
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.BIRTHDAY
     *
     * @return the value of RAP_USER.BIRTHDAY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.BIRTHDAY
     *
     * @param birthday the value for RAP_USER.BIRTHDAY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.firePropertyChange("birthday",birthday);
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.CREATED_BY
     *
     * @return the value of RAP_USER.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.CREATED_BY
     *
     * @param createdBy the value for RAP_USER.CREATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCreatedBy(Integer createdBy) {
        this.firePropertyChange("createdBy",createdBy);
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.CREATION_DATE
     *
     * @return the value of RAP_USER.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.CREATION_DATE
     *
     * @param creationDate the value for RAP_USER.CREATION_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.firePropertyChange("creationDate",creationDate);
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.LAST_UPDATE_DATE
     *
     * @return the value of RAP_USER.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for RAP_USER.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.firePropertyChange("lastUpdateDate",lastUpdateDate);
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.LAST_UPDATED_BY
     *
     * @return the value of RAP_USER.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public Integer getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for RAP_USER.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setLastUpdatedBy(Integer lastUpdatedBy) {
        this.firePropertyChange("lastUpdatedBy",lastUpdatedBy);
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.MEMO
     *
     * @return the value of RAP_USER.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.MEMO
     *
     * @param memo the value for RAP_USER.MEMO
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    public void setMemo(String memo) {
        this.firePropertyChange("memo",memo);
        this.memo = memo;
    }

    public Integer getPrimaryKey() {
        return this.userId;
    }

    public void setPrimaryKey(Integer pkValue) {
        this.setUserId(pkValue);
    }
}