package com.github.jamsa.rap.model;

import com.github.jamsa.rap.core.model.BaseEntity;

public class User extends BaseEntity<Long> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.ID
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.FULLNAME
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.PASSWORD
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_USER.USERNAME
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.ID
     *
     * @return the value of RAP_USER.ID
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.ID
     *
     * @param id the value for RAP_USER.ID
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public void setId(Long id) {
        this.firePropertyChange("id",id);
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.FULLNAME
     *
     * @return the value of RAP_USER.FULLNAME
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.FULLNAME
     *
     * @param fullname the value for RAP_USER.FULLNAME
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public void setFullname(String fullname) {
        this.firePropertyChange("fullname",fullname);
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.PASSWORD
     *
     * @return the value of RAP_USER.PASSWORD
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.PASSWORD
     *
     * @param password the value for RAP_USER.PASSWORD
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public void setPassword(String password) {
        this.firePropertyChange("password",password);
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_USER.USERNAME
     *
     * @return the value of RAP_USER.USERNAME
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_USER.USERNAME
     *
     * @param username the value for RAP_USER.USERNAME
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    public void setUsername(String username) {
        this.firePropertyChange("username",username);
        this.username = username;
    }

    public Long getPrimaryKey() {
        return this.id;
    }

    public void setPrimaryKey(Long pkValue) {
        this.setId(pkValue);
    }
}