package com.github.jamsa.rap.model;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.WORK_TICKET_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal workTicketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.TICKET_MODEL_CODE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String ticketModelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.STAUTS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String stauts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.MAIN_TICKET_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal mainTicketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.DETAIL_CONTENT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String detailContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.CONTENT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.EQUIP_KKS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String equipKks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ISQUALIFIED
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String isqualified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.SOURCE_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.SAME_STANDARD
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String sameStandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ORG_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.DEPT_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.TICKET_NUMBER
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String ticketNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.SERIAL_NUMBER
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.PAGE_COUNT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal pageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.CREATE_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.CREATE_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String createMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.WORKORDER_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String workorderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.SIGN_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String signMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.SIGN_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.SIGN_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String signManDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.RECEIVE_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String receiveMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.RECEIVE_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String receiveManDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.RECEIVE_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.PERMIT_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String permitMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.PERMIT_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date permitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.PERMIT_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String permitManDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.CLASS_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.FINISH_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.WORKER_COUNT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal workerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.STANDART_STATUS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String standartStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.STANDART_CHECK_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String standartCheckMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.STANDART_CHECK_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date standartCheckTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Long lastUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.CREATION_DATE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.CREATED_BY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.LAST_UPDATE_LOGIN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private Long lastUpdateLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE1
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE2
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE3
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE4
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE5
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE6
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE7
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE8
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE9
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE10
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE11
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE12
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE13
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE14
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ATTRIBUTE15
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String attribute15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.ITEM_KEY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String itemKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.PERMIT_MAN_CLASS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private String permitManClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIQ_TT_WORK_TICKET.PRINCIPAL
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    private BigDecimal principal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.WORK_TICKET_ID
     *
     * @return the value of DIQ_TT_WORK_TICKET.WORK_TICKET_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getWorkTicketId() {
        return workTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.WORK_TICKET_ID
     *
     * @param workTicketId the value for DIQ_TT_WORK_TICKET.WORK_TICKET_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setWorkTicketId(BigDecimal workTicketId) {
        this.workTicketId = workTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.TICKET_MODEL_CODE
     *
     * @return the value of DIQ_TT_WORK_TICKET.TICKET_MODEL_CODE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getTicketModelCode() {
        return ticketModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.TICKET_MODEL_CODE
     *
     * @param ticketModelCode the value for DIQ_TT_WORK_TICKET.TICKET_MODEL_CODE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setTicketModelCode(String ticketModelCode) {
        this.ticketModelCode = ticketModelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.STAUTS
     *
     * @return the value of DIQ_TT_WORK_TICKET.STAUTS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getStauts() {
        return stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.STAUTS
     *
     * @param stauts the value for DIQ_TT_WORK_TICKET.STAUTS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setStauts(String stauts) {
        this.stauts = stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.MAIN_TICKET_ID
     *
     * @return the value of DIQ_TT_WORK_TICKET.MAIN_TICKET_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getMainTicketId() {
        return mainTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.MAIN_TICKET_ID
     *
     * @param mainTicketId the value for DIQ_TT_WORK_TICKET.MAIN_TICKET_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setMainTicketId(BigDecimal mainTicketId) {
        this.mainTicketId = mainTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.DETAIL_CONTENT
     *
     * @return the value of DIQ_TT_WORK_TICKET.DETAIL_CONTENT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getDetailContent() {
        return detailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.DETAIL_CONTENT
     *
     * @param detailContent the value for DIQ_TT_WORK_TICKET.DETAIL_CONTENT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setDetailContent(String detailContent) {
        this.detailContent = detailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.CONTENT
     *
     * @return the value of DIQ_TT_WORK_TICKET.CONTENT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.CONTENT
     *
     * @param content the value for DIQ_TT_WORK_TICKET.CONTENT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.EQUIP_KKS
     *
     * @return the value of DIQ_TT_WORK_TICKET.EQUIP_KKS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getEquipKks() {
        return equipKks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.EQUIP_KKS
     *
     * @param equipKks the value for DIQ_TT_WORK_TICKET.EQUIP_KKS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setEquipKks(String equipKks) {
        this.equipKks = equipKks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ISQUALIFIED
     *
     * @return the value of DIQ_TT_WORK_TICKET.ISQUALIFIED
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getIsqualified() {
        return isqualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ISQUALIFIED
     *
     * @param isqualified the value for DIQ_TT_WORK_TICKET.ISQUALIFIED
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setIsqualified(String isqualified) {
        this.isqualified = isqualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.SOURCE_ID
     *
     * @return the value of DIQ_TT_WORK_TICKET.SOURCE_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.SOURCE_ID
     *
     * @param sourceId the value for DIQ_TT_WORK_TICKET.SOURCE_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setSourceId(BigDecimal sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.SAME_STANDARD
     *
     * @return the value of DIQ_TT_WORK_TICKET.SAME_STANDARD
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getSameStandard() {
        return sameStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.SAME_STANDARD
     *
     * @param sameStandard the value for DIQ_TT_WORK_TICKET.SAME_STANDARD
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setSameStandard(String sameStandard) {
        this.sameStandard = sameStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ORG_ID
     *
     * @return the value of DIQ_TT_WORK_TICKET.ORG_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ORG_ID
     *
     * @param orgId the value for DIQ_TT_WORK_TICKET.ORG_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.DEPT_ID
     *
     * @return the value of DIQ_TT_WORK_TICKET.DEPT_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.DEPT_ID
     *
     * @param deptId the value for DIQ_TT_WORK_TICKET.DEPT_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setDeptId(BigDecimal deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.TICKET_NUMBER
     *
     * @return the value of DIQ_TT_WORK_TICKET.TICKET_NUMBER
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.TICKET_NUMBER
     *
     * @param ticketNumber the value for DIQ_TT_WORK_TICKET.TICKET_NUMBER
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.SERIAL_NUMBER
     *
     * @return the value of DIQ_TT_WORK_TICKET.SERIAL_NUMBER
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.SERIAL_NUMBER
     *
     * @param serialNumber the value for DIQ_TT_WORK_TICKET.SERIAL_NUMBER
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.PAGE_COUNT
     *
     * @return the value of DIQ_TT_WORK_TICKET.PAGE_COUNT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getPageCount() {
        return pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.PAGE_COUNT
     *
     * @param pageCount the value for DIQ_TT_WORK_TICKET.PAGE_COUNT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setPageCount(BigDecimal pageCount) {
        this.pageCount = pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.CREATE_TIME
     *
     * @return the value of DIQ_TT_WORK_TICKET.CREATE_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.CREATE_TIME
     *
     * @param createTime the value for DIQ_TT_WORK_TICKET.CREATE_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.CREATE_MAN
     *
     * @return the value of DIQ_TT_WORK_TICKET.CREATE_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.CREATE_MAN
     *
     * @param createMan the value for DIQ_TT_WORK_TICKET.CREATE_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.WORKORDER_ID
     *
     * @return the value of DIQ_TT_WORK_TICKET.WORKORDER_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getWorkorderId() {
        return workorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.WORKORDER_ID
     *
     * @param workorderId the value for DIQ_TT_WORK_TICKET.WORKORDER_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setWorkorderId(String workorderId) {
        this.workorderId = workorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.SIGN_MAN
     *
     * @return the value of DIQ_TT_WORK_TICKET.SIGN_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getSignMan() {
        return signMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.SIGN_MAN
     *
     * @param signMan the value for DIQ_TT_WORK_TICKET.SIGN_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setSignMan(String signMan) {
        this.signMan = signMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.SIGN_TIME
     *
     * @return the value of DIQ_TT_WORK_TICKET.SIGN_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.SIGN_TIME
     *
     * @param signTime the value for DIQ_TT_WORK_TICKET.SIGN_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.SIGN_MAN_DEPT
     *
     * @return the value of DIQ_TT_WORK_TICKET.SIGN_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getSignManDept() {
        return signManDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.SIGN_MAN_DEPT
     *
     * @param signManDept the value for DIQ_TT_WORK_TICKET.SIGN_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setSignManDept(String signManDept) {
        this.signManDept = signManDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.RECEIVE_MAN
     *
     * @return the value of DIQ_TT_WORK_TICKET.RECEIVE_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getReceiveMan() {
        return receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.RECEIVE_MAN
     *
     * @param receiveMan the value for DIQ_TT_WORK_TICKET.RECEIVE_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setReceiveMan(String receiveMan) {
        this.receiveMan = receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.RECEIVE_MAN_DEPT
     *
     * @return the value of DIQ_TT_WORK_TICKET.RECEIVE_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getReceiveManDept() {
        return receiveManDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.RECEIVE_MAN_DEPT
     *
     * @param receiveManDept the value for DIQ_TT_WORK_TICKET.RECEIVE_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setReceiveManDept(String receiveManDept) {
        this.receiveManDept = receiveManDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.RECEIVE_TIME
     *
     * @return the value of DIQ_TT_WORK_TICKET.RECEIVE_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.RECEIVE_TIME
     *
     * @param receiveTime the value for DIQ_TT_WORK_TICKET.RECEIVE_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.PERMIT_MAN
     *
     * @return the value of DIQ_TT_WORK_TICKET.PERMIT_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getPermitMan() {
        return permitMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.PERMIT_MAN
     *
     * @param permitMan the value for DIQ_TT_WORK_TICKET.PERMIT_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setPermitMan(String permitMan) {
        this.permitMan = permitMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.PERMIT_TIME
     *
     * @return the value of DIQ_TT_WORK_TICKET.PERMIT_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getPermitTime() {
        return permitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.PERMIT_TIME
     *
     * @param permitTime the value for DIQ_TT_WORK_TICKET.PERMIT_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setPermitTime(Date permitTime) {
        this.permitTime = permitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.PERMIT_MAN_DEPT
     *
     * @return the value of DIQ_TT_WORK_TICKET.PERMIT_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getPermitManDept() {
        return permitManDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.PERMIT_MAN_DEPT
     *
     * @param permitManDept the value for DIQ_TT_WORK_TICKET.PERMIT_MAN_DEPT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setPermitManDept(String permitManDept) {
        this.permitManDept = permitManDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.CLASS_ID
     *
     * @return the value of DIQ_TT_WORK_TICKET.CLASS_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.CLASS_ID
     *
     * @param classId the value for DIQ_TT_WORK_TICKET.CLASS_ID
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.FINISH_TIME
     *
     * @return the value of DIQ_TT_WORK_TICKET.FINISH_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.FINISH_TIME
     *
     * @param finishTime the value for DIQ_TT_WORK_TICKET.FINISH_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.WORKER_COUNT
     *
     * @return the value of DIQ_TT_WORK_TICKET.WORKER_COUNT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getWorkerCount() {
        return workerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.WORKER_COUNT
     *
     * @param workerCount the value for DIQ_TT_WORK_TICKET.WORKER_COUNT
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setWorkerCount(BigDecimal workerCount) {
        this.workerCount = workerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.STANDART_STATUS
     *
     * @return the value of DIQ_TT_WORK_TICKET.STANDART_STATUS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getStandartStatus() {
        return standartStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.STANDART_STATUS
     *
     * @param standartStatus the value for DIQ_TT_WORK_TICKET.STANDART_STATUS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setStandartStatus(String standartStatus) {
        this.standartStatus = standartStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.STANDART_CHECK_MAN
     *
     * @return the value of DIQ_TT_WORK_TICKET.STANDART_CHECK_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getStandartCheckMan() {
        return standartCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.STANDART_CHECK_MAN
     *
     * @param standartCheckMan the value for DIQ_TT_WORK_TICKET.STANDART_CHECK_MAN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setStandartCheckMan(String standartCheckMan) {
        this.standartCheckMan = standartCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.STANDART_CHECK_TIME
     *
     * @return the value of DIQ_TT_WORK_TICKET.STANDART_CHECK_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getStandartCheckTime() {
        return standartCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.STANDART_CHECK_TIME
     *
     * @param standartCheckTime the value for DIQ_TT_WORK_TICKET.STANDART_CHECK_TIME
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setStandartCheckTime(Date standartCheckTime) {
        this.standartCheckTime = standartCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.LAST_UPDATE_DATE
     *
     * @return the value of DIQ_TT_WORK_TICKET.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for DIQ_TT_WORK_TICKET.LAST_UPDATE_DATE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.LAST_UPDATED_BY
     *
     * @return the value of DIQ_TT_WORK_TICKET.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for DIQ_TT_WORK_TICKET.LAST_UPDATED_BY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.CREATION_DATE
     *
     * @return the value of DIQ_TT_WORK_TICKET.CREATION_DATE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.CREATION_DATE
     *
     * @param creationDate the value for DIQ_TT_WORK_TICKET.CREATION_DATE
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.CREATED_BY
     *
     * @return the value of DIQ_TT_WORK_TICKET.CREATED_BY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.CREATED_BY
     *
     * @param createdBy the value for DIQ_TT_WORK_TICKET.CREATED_BY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.LAST_UPDATE_LOGIN
     *
     * @return the value of DIQ_TT_WORK_TICKET.LAST_UPDATE_LOGIN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public Long getLastUpdateLogin() {
        return lastUpdateLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.LAST_UPDATE_LOGIN
     *
     * @param lastUpdateLogin the value for DIQ_TT_WORK_TICKET.LAST_UPDATE_LOGIN
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setLastUpdateLogin(Long lastUpdateLogin) {
        this.lastUpdateLogin = lastUpdateLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE1
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE1
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE1
     *
     * @param attribute1 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE1
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE2
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE2
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE2
     *
     * @param attribute2 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE2
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE3
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE3
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE3
     *
     * @param attribute3 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE3
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE4
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE4
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE4
     *
     * @param attribute4 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE4
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE5
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE5
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE5
     *
     * @param attribute5 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE5
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE6
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE6
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE6
     *
     * @param attribute6 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE6
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE7
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE7
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE7
     *
     * @param attribute7 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE7
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE8
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE8
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE8
     *
     * @param attribute8 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE8
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE9
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE9
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE9
     *
     * @param attribute9 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE9
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE10
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE10
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE10
     *
     * @param attribute10 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE10
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE11
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE11
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute11() {
        return attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE11
     *
     * @param attribute11 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE11
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE12
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE12
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute12() {
        return attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE12
     *
     * @param attribute12 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE12
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE13
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE13
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute13() {
        return attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE13
     *
     * @param attribute13 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE13
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE14
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE14
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute14() {
        return attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE14
     *
     * @param attribute14 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE14
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE15
     *
     * @return the value of DIQ_TT_WORK_TICKET.ATTRIBUTE15
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getAttribute15() {
        return attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ATTRIBUTE15
     *
     * @param attribute15 the value for DIQ_TT_WORK_TICKET.ATTRIBUTE15
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.ITEM_KEY
     *
     * @return the value of DIQ_TT_WORK_TICKET.ITEM_KEY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getItemKey() {
        return itemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.ITEM_KEY
     *
     * @param itemKey the value for DIQ_TT_WORK_TICKET.ITEM_KEY
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setItemKey(String itemKey) {
        this.itemKey = itemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.PERMIT_MAN_CLASS
     *
     * @return the value of DIQ_TT_WORK_TICKET.PERMIT_MAN_CLASS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public String getPermitManClass() {
        return permitManClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.PERMIT_MAN_CLASS
     *
     * @param permitManClass the value for DIQ_TT_WORK_TICKET.PERMIT_MAN_CLASS
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setPermitManClass(String permitManClass) {
        this.permitManClass = permitManClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIQ_TT_WORK_TICKET.PRINCIPAL
     *
     * @return the value of DIQ_TT_WORK_TICKET.PRINCIPAL
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public BigDecimal getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIQ_TT_WORK_TICKET.PRINCIPAL
     *
     * @param principal the value for DIQ_TT_WORK_TICKET.PRINCIPAL
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    public void setPrincipal(BigDecimal principal) {
        this.principal = principal;
    }
}