package com.github.jamsa.rap.meta.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.meta.model.RapMetaTableField;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RapMetaTableFieldMapper extends BaseMapper<RapMetaTableField, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int deleteByPrimaryKey(Integer fieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insert(RapMetaTableField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insertSelective(RapMetaTableField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    RapMetaTableField selectByPrimaryKey(Integer fieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKeySelective(RapMetaTableField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKey(RapMetaTableField record);

    /** @mbggenerated */
    List<RapMetaTableField> selectByCondition(RapMetaTableField condition);


    List<RapMetaTableField> selectByModelId(Long modelId);
}