package com.github.jamsa.rap.meta.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.meta.model.RapMetaViewField;
import org.apache.ibatis.annotations.Mapper;

import java.util.Arrays;
import java.util.List;

@Mapper
public interface RapMetaViewFieldMapper extends BaseMapper<RapMetaViewField, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int deleteByPrimaryKey(Integer fieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insert(RapMetaViewField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insertSelective(RapMetaViewField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    RapMetaViewField selectByPrimaryKey(Integer fieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKeySelective(RapMetaViewField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_FIELD
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKey(RapMetaViewField record);

    /** @mbggenerated */
    List<RapMetaViewField> selectByCondition(RapMetaViewField condition);

    List<RapMetaViewField> selectByModelId(Long modelId);

}