package com.github.jamsa.rap.meta.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.meta.model.RapMetaViewObject;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RapMetaViewObjectMapper extends BaseMapper<RapMetaViewObject, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_OBJECT
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int deleteByPrimaryKey(Integer viewObjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_OBJECT
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insert(RapMetaViewObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_OBJECT
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insertSelective(RapMetaViewObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_OBJECT
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    RapMetaViewObject selectByPrimaryKey(Integer viewObjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_OBJECT
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKeySelective(RapMetaViewObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_OBJECT
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(RapMetaViewObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_VIEW_OBJECT
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKey(RapMetaViewObject record);

    /** @mbggenerated */
    List<RapMetaViewObject> selectByCondition(RapMetaViewObject condition);
}