package com.github.jamsa.rap.meta.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.meta.model.RapMetaTable;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RapMetaTableMapper extends BaseMapper<RapMetaTable, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int deleteByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insert(RapMetaTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insertSelective(RapMetaTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    RapMetaTable selectByPrimaryKey(Integer tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKeySelective(RapMetaTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_TABLE
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKey(RapMetaTable record);

    /** @mbggenerated */
    List<RapMetaTable> selectByCondition(RapMetaTable condition);

    List<RapMetaTable> selectByModelId(Long modelId);
}