package com.github.jamsa.rap.meta.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.meta.model.RapMetaModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RapMetaModelMapper extends BaseMapper<RapMetaModel, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_MODEL
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_MODEL
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insert(RapMetaModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_MODEL
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int insertSelective(RapMetaModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_MODEL
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    RapMetaModel selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_MODEL
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKeySelective(RapMetaModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_META_MODEL
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    int updateByPrimaryKey(RapMetaModel record);

    /** @mbggenerated */
    List<RapMetaModel> selectByCondition(RapMetaModel condition);

    RapMetaModel selectByModelCode(String modelCode);
}