package com.github.jamsa.rap.meta.model;

public class RapMetaModelViewObjectKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_META_MODEL_OBJECT.VIEW_OBJECT_ID
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    private Integer viewObjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAP_META_MODEL_OBJECT.MODEL_ID
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    private Integer modelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_META_MODEL_OBJECT.VIEW_OBJECT_ID
     *
     * @return the value of RAP_META_MODEL_OBJECT.VIEW_OBJECT_ID
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    public Integer getViewObjectId() {
        return viewObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_META_MODEL_OBJECT.VIEW_OBJECT_ID
     *
     * @param viewObjectId the value for RAP_META_MODEL_OBJECT.VIEW_OBJECT_ID
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    public void setViewObjectId(Integer viewObjectId) {
        this.viewObjectId = viewObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAP_META_MODEL_OBJECT.MODEL_ID
     *
     * @return the value of RAP_META_MODEL_OBJECT.MODEL_ID
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAP_META_MODEL_OBJECT.MODEL_ID
     *
     * @param modelId the value for RAP_META_MODEL_OBJECT.MODEL_ID
     *
     * @mbggenerated Sat Oct 13 19:35:54 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }
}