package com.github.jamsa.rap.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.model.DictValue;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DictValueMapper extends BaseMapper<DictValue, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_DICT_VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int deleteByPrimaryKey(Integer dictValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_DICT_VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int insert(DictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_DICT_VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int insertSelective(DictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_DICT_VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    DictValue selectByPrimaryKey(Integer dictValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_DICT_VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int updateByPrimaryKeySelective(DictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_DICT_VALUE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int updateByPrimaryKey(DictValue record);

    /** @mbggenerated */
    List<DictValue> selectByCondition(DictValue condition);
}