package com.github.jamsa.rap.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.model.Resource;
import java.util.List;

public interface ResourceMapper extends BaseMapper<Resource, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_RESOURCE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int deleteByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_RESOURCE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_RESOURCE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_RESOURCE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    Resource selectByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_RESOURCE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_RESOURCE
     *
     * @mbggenerated Thu Aug 25 14:35:40 CST 2016
     */
    int updateByPrimaryKey(Resource record);

    /** @mbggenerated */
    List<Resource> selectByCondition(Resource condition);
}