package com.github.jamsa.rap.mapper;

import com.github.jamsa.rap.model.User;
import java.math.BigDecimal;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIQ_TT_WORK_TICKET
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal workTicketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIQ_TT_WORK_TICKET
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIQ_TT_WORK_TICKET
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIQ_TT_WORK_TICKET
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    User selectByPrimaryKey(BigDecimal workTicketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIQ_TT_WORK_TICKET
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DIQ_TT_WORK_TICKET
     *
     * @mbggenerated Wed Jul 06 09:32:15 CST 2016
     */
    int updateByPrimaryKey(User record);

    List<User> selectForPage();
}