package com.github.jamsa.rap.mapper;

import com.github.jamsa.rap.core.mapper.BaseMapper;
import com.github.jamsa.rap.model.User;
import java.util.List;

public interface UserMapper extends BaseMapper<User, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_USER
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_USER
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_USER
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_USER
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_USER
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAP_USER
     *
     * @mbggenerated Wed Aug 24 14:41:51 CST 2016
     */
    int updateByPrimaryKey(User record);

    /** @mbggenerated */
    List<User> selectByCondition(User condition);
}